FROM golang:1.13 as builder
WORKDIR /src
ENV CGO_ENABLED=0
COPY pkg/jindra/tools/crij /src
RUN go get -v && go test . && go build -x ./... && go build ./cmd/crij

FROM alpine
COPY --from=builder /src/crij /jindra/contrib/crij
