FROM golang:1.13 as builder

WORKDIR /src
ENV CGO_ENABLED=0
COPY . /src/
RUN go get -v && go test . && go build -x ./... && go build -o bin/crij ./cmd/crij

FROM alpine
COPY --from=builder /src/bin/crij /jindra/contrib/crij
