apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: jindrapipelines.jindra.io
spec:
  group: jindra.io
  names:
    kind: JindraPipeline
    listKind: JindraPipelineList
    plural: jindrapipelines
    singular: jindrapipeline
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          properties:
            onError:
              type: object
            onSuccess:
              type: object
            resources:
              properties:
                containers:
                  items:
                    type: object
                  type: array
                triggers:
                  items:
                    properties:
                      name:
                        type: string
                      schedule:
                        type: string
                    required:
                    - name
                    - schedule
                    type: object
                  type: array
              required:
              - triggers
              - containers
              type: object
            stages:
              items:
                type: object
              type: array
          required:
          - resources
          - stages
          - onSuccess
          - onError
          type: object
        status:
          properties:
            buildNo:
              format: int64
              type: integer
          required:
          - buildNo
          type: object
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
