apiVersion: apps/v1
kind: Deployment
metadata:
  name: jindra-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: jindra
  template:
    metadata:
      labels:
        name: jindra
        jindra-component: operator
    spec:
      serviceAccountName: jindra
      containers:
        - name: jindra
          # Replace this with the built image name
          image: jindra/jindra
          command:
          - jindra
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "jindra"
