apiVersion: jindra.io/v1alpha1
kind: JindraPipeline
metadata:
  name: minimal-pipeline
spec:
  stages:
    - metadata:
        name: one
      spec:
        containers:
          - name: test
            image: alpine
            command: ["sh", "-c", "sleep 3600"]
