---
apiVersion: v1
kind: ServiceAccount
metadata:
  creationTimestamp: null
  name: jindra-runner
  namespace: jindra
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  creationTimestamp: null
  name: jindra-runner
rules:
- apiGroups:
  - "batch"
  resources:
  - jobs
  verbs:
  - get
  - patch
  - list
- apiGroups:
  - ""
  resources:
  - pods
  - pods/status
  - pods/log
  - secrets
  - configmaps
  - jobs
  verbs:
  - get
  - update
  - patch
  - list
  - watch
  - create
  - delete
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  creationTimestamp: null
  name: jindra-runner
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: jindra-runner
subjects:
- kind: ServiceAccount
  name: jindra-runner
