apiVersion: v1
kind: Pod
metadata:
  name: jindra-git-resource
spec:
  volumes:
  - name: git
    emptyDir: {}
  - name: jindra-tools
    configMap:
      name: jindra-tools

  initContainers:
  - name: jindra-git-resource
    image: concourse/git-resource
    args:
      - sh
      - -c
      - "sh /jindra/tools/env-to-concourse-resources-json.sh in | /opt/resource/in /jindra/resources/git"
    env:
      - name: in_source_uri
        value: "git@github.com:kesselborn/http-fs"
      - name: in_source_private_key
        valueFrom: { secretKeyRef: {name: deploy-key, key: key}}
    volumeMounts:
    - mountPath: /jindra/resources/git
      name: git
    - mountPath: /jindra/tools
      name: jindra-tools

  containers:
  - name: test
    image: alpine
    args:
      - sh
      - -c
      - sleep 3600
    volumeMounts:
    - mountPath: /jindra/resources/git
      name: git
