apiVersion: v1
kind: JindraPipeline
metadata:
  name: MyPipeline
spec:
  resources:
    triggers: <[]Tokens> # Tokens == resources
    # jeder resources implementiert ein oder mehr von in, out, check. Konfiguration ist abhängig von
    # der Resources (z.B. sollte das check Interval evtl. konfigurierbar sein)
    containers: <[]Object> # Kind: pod.spec.container: name optional, mountVolume muss <name> volume mounten
  stages:
    - metadata:
        name: <string>
        annotations:
          jindra.io/inputs: <[]Tokens> # Tokens == resources
          jindra.io/outputs: <[]Tokens> # Tokens == resources
        #...
      spec: <Object> # pod.spec
  on_failure:
    <pod>
  on_success:
    <pod>
