// +build !ignore_autogenerated

// Code generated by operator-sdk. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *JindraPipeline) DeepCopyInto(out *JindraPipeline) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	out.Status = in.Status
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new JindraPipeline.
func (in *JindraPipeline) DeepCopy() *JindraPipeline {
	if in == nil {
		return nil
	}
	out := new(JindraPipeline)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *JindraPipeline) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *JindraPipelineList) DeepCopyInto(out *JindraPipelineList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	out.ListMeta = in.ListMeta
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]JindraPipeline, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new JindraPipelineList.
func (in *JindraPipelineList) DeepCopy() *JindraPipelineList {
	if in == nil {
		return nil
	}
	out := new(JindraPipelineList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *JindraPipelineList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *JindraPipelineSpec) DeepCopyInto(out *JindraPipelineSpec) {
	*out = *in
	if in.Resources != nil {
		in, out := &in.Resources, &out.Resources
		*out = make([]JindraPipelineSpecTrigger, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new JindraPipelineSpec.
func (in *JindraPipelineSpec) DeepCopy() *JindraPipelineSpec {
	if in == nil {
		return nil
	}
	out := new(JindraPipelineSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *JindraPipelineSpecTrigger) DeepCopyInto(out *JindraPipelineSpecTrigger) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new JindraPipelineSpecTrigger.
func (in *JindraPipelineSpecTrigger) DeepCopy() *JindraPipelineSpecTrigger {
	if in == nil {
		return nil
	}
	out := new(JindraPipelineSpecTrigger)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *JindraPipelineStatus) DeepCopyInto(out *JindraPipelineStatus) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new JindraPipelineStatus.
func (in *JindraPipelineStatus) DeepCopy() *JindraPipelineStatus {
	if in == nil {
		return nil
	}
	out := new(JindraPipelineStatus)
	in.DeepCopyInto(out)
	return out
}
